### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/CombatLog#1]
- [ ] Kill players if they log out / disconnect from the server.

- [ ] Disable players from using commands in pvp, but allow some. Make it configurable :D

- [ ] Add messages for CombatLog, ex once they get combatlogged, it will show in chat. Add configuration to set it to broadcast to world or whole server.

**Comment by SalmonGER** [comment]
Hmm killing players when they log out. Must test that. Other stuff should be easily done.
